In [1]:
import pandas as pd
from classify import Classifier
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

/home/lam/miniforge3/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

cuda

In [5]:
clf = Classifier("cfg/car_quality.yaml")  # load task config
ckpt_path = (r"output/20260729/CarQuality.Classification/mobilenet_v3_small"
             r"/version_1/checkpoints/best_acc_epoch=97-val_loss=0.047-val_acc=0.992.ckpt")
results = clf.predict(
    source="datasets/dataset",
    ckpt_path=ckpt_path,
    num_classes=2,
    precision="32",
    resize=128,
)

df = pd.DataFrame(results)
df.to_csv("results.csv", index=False)

2026-08-07 13:25:44 | INFO     | classify — Classifier ready — model=mobilenet_v3_small  classes=0
2026-08-07 13:25:44 | INFO     | classify.engine.predictor — Loading model 'mobilenet_v3_small' from 'output/20260729/CarQuality.Classification/mobilenet_v3_small/version_1/checkpoints/best_acc_epoch=97-val_loss=0.047-val_acc=0.992.ckpt' on cuda…
2026-08-07 13:25:44 | INFO     | classify.models.lightning_module — Loaded pretrained weights from 'output/20260729/CarQuality.Classification/mobilenet_v3_small/version_1/checkpoints/best_acc_epoch=97-val_loss=0.047-val_acc=0.992.ckpt'.
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0028e49b-4e02-4ed1-b9c6-550f43e08a78_aligned.jpg  →  class=0  score=0.9998
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   00dd301c-c6c7-4fca-b7c6-30311a9c816c_aligned.jpg  →  class=0  score=1.0000
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0107d7c0-d826-40a7-8a5f-3fd14181b28f.jpg  →  class=0  score=0.9987
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   015a6379-065e-4ce3-a2e5-81d96056f166.jpg  →  class=0  score=0.9541
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   01add812-5843-4f75-a2fa-94d82a6700f8.jpg  →  class=0  score=0.9819
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   01d44f82-90ca-4357-8b93-2d851694817c_aligned.jpg  →  class=0  score=0.9995
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0347dec7-b0a0-4359-8f8b-fd37ab6f7709.jpg  →  class=0  score=0.9966
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   04484679-58bb-4afb-bc01-aed448983e03.jpg  →  class=0  score=0.9996
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   05293e08-e874-4e92-af5d-9af06a0cc599.jpg  →  class=0  score=0.9998
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0558e3dc-d8f2-4c31-8404-c083be2c049f.jpg  →  class=0  score=0.9984
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   05b82b68-d29f-4d2a-bef2-ad1f0a277114.jpg  →  class=0  score=0.9592
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   08166a23-0aaf-4015-9725-b39f504f773f.jpg  →  class=0  score=0.9981
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0881dbd9-7fde-4113-84ef-bc03ffa0d149.jpg  →  class=0  score=1.0000
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   098f7def-c73c-4d06-b7ce-a115cb8f005a_aligned.jpg  →  class=0  score=0.9999
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   099680da-79e4-49f2-8a28-f1120ab43ebe.jpg  →  class=0  score=0.9947
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0a2c1dcf-9676-40fc-8aad-61b5266e3891.jpg  →  class=0  score=0.9564
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0a553170-011b-41ad-b546-0e503f90d519_aligned.jpg  →  class=0  score=0.9997
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0a5facb8-10bf-4e47-9fa2-3d22ea409648.jpg  →  class=0  score=0.9957
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0af3d883-33ca-4be5-a603-2171e310e9bc_aligned.jpg  →  class=0  score=0.9998
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0b1be356-742a-4483-bb0b-c02e2dda8c6b.jpg  →  class=0  score=0.9993
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0b6cf835-5135-42e9-86ac-eed5efdd1634_aligned.jpg  →  class=0  score=0.9993
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0b7cb467-0ca4-4acb-a70a-e577e101574b_aligned.jpg  →  class=0  score=1.0000
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0c9e0ef3-3830-4588-9142-270002b26c72_aligned.jpg  →  class=0  score=1.0000
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0ca3f129-9818-47bf-9027-37a7b7a14193_aligned.jpg  →  class=0  score=0.9990
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0d43389a-b59d-4504-b9bd-9111dfdf9840.jpg  →  class=0  score=0.9998
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0d633555-9172-4603-88bd-15ff317885e6_aligned.jpg  →  class=0  score=0.9993
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0da4efa6-5ba7-42a6-91c9-34484a307f56.jpg  →  class=0  score=0.9995
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0dd9ebb0-d300-4d3a-9d44-98b27c2fed4c_aligned.jpg  →  class=0  score=0.9995
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0e9ff7de-75d0-40b2-b130-af5bbfa8d024.jpg  →  class=0  score=0.9998
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0edebf99-ff27-4ad5-a65b-3b4ded1a3be7.jpg  →  class=0  score=0.9987
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0ee6d6a6-2d10-438b-905c-af2e6417c40f.jpg  →  class=0  score=0.9998
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0ef61899-69ff-4f45-a510-86e06e40cdda.jpg  →  class=0  score=0.9993
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0f07ecc7-b497-4009-955c-0fbbbaf41036_aligned.jpg  →  class=0  score=0.9992
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0f37f21e-4d4c-48b2-bb7f-14d866a736e3_aligned.jpg  →  class=0  score=0.9845
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   0fa75374-3218-4a44-a8cb-05361b8a7e8f.jpg  →  class=0  score=0.9981
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1 (1).jpg  →  class=0  score=0.9979
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1 (3)_0.jpg  →  class=0  score=0.9914
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1 (8) dated_0.jpg  →  class=1  score=0.9997
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1 (8) dated_1.jpg  →  class=1  score=1.0000
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1 TONG THE  (8).jpg  →  class=1  score=0.9690
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1 TONG THE  (8)_0.jpg  →  class=1  score=0.9999
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1 TONG THE  (8)_1.jpg  →  class=1  score=0.9883
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1001c5ff-8363-4409-b44f-3217b1d99625.jpg  →  class=0  score=0.8412
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   10288de4-c6cd-4c92-9383-87b0f10d492f_aligned.jpg  →  class=0  score=0.9927
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   109b6810-5967-48fe-a8b3-b57639996348_aligned.jpg  →  class=0  score=0.9998
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   10a863c9-0c08-4188-9a31-27eae9d19f43.jpg  →  class=0  score=0.8657
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   10feb726-c926-4004-8721-368bc4ade684_aligned.jpg  →  class=0  score=1.0000
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1291ab6e-a403-4901-9d88-6daf815dd731_aligned.jpg  →  class=0  score=1.0000
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   131c25cc-4977-47e4-904c-0439499061da.jpg  →  class=0  score=0.9941
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   14336d5d-f111-45e7-b254-c72b43d05896_aligned.jpg  →  class=0  score=0.9994
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   145f6c22-0b3d-41ad-a41e-f5c6f8dd958a_aligned.jpg  →  class=0  score=0.9988
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1468486733824_11240_0.jpg  →  class=1  score=0.9979
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1468932580342_13072_0.jpg  →  class=0  score=0.9998
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1469429139191_14202_0.jpg  →  class=0  score=0.9985
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1469618546810_15097_1.jpg  →  class=1  score=0.9999
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1470037224635_15944_0.jpg  →  class=0  score=0.9997
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1470039818684_15971_1.jpg  →  class=1  score=0.9990
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1470210967795_16203_0.jpg  →  class=1  score=0.9953
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1470210987767_16350.jpg  →  class=0  score=0.9998
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1470295180256_16539_0.jpg  →  class=0  score=0.9996
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1471861686634_20041.jpg  →  class=0  score=0.9998
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1473152626281_23391.jpg  →  class=1  score=0.9863
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1473843077455_26330_1.jpg  →  class=1  score=0.9987
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1476197219764_32888_0.jpg  →  class=1  score=0.9980
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1476267278670_33132_1.jpg  →  class=1  score=0.9995
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1476340158031_33496_0.jpg  →  class=0  score=0.9995
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1476340747997_33524_0.jpg  →  class=1  score=0.9954
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1476958922728_34948_0.jpg  →  class=1  score=0.9998
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1477105354275_35279_1.jpg  →  class=1  score=0.9988
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1479125511611_39662_0.jpg  →  class=1  score=0.9852
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1479125825126_39669_0.jpg  →  class=1  score=0.9904
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   152a4f0c-b882-4c26-92ba-6eadf9b85aaf.jpg  →  class=0  score=0.9747
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   154e7b3f-4e2f-4583-9f0a-a3cf1bd51ed2_aligned.jpg  →  class=0  score=0.9994
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   159e7a73-40f7-4507-ad9e-c95944b94329.jpg  →  class=0  score=0.9997
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   15ecd730-a547-491b-8ba5-b1dc532a7307.jpg  →  class=0  score=0.9997
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1613717080545_0.jpg  →  class=1  score=1.0000
2026-08-07 13:25:45 | INFO     | classify.engine.predictor —   1615598943287_0.jpg  →  class=0  score=0.9988
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1617070256577.jpg  →  class=0  score=0.9992
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1617174527447.jpg  →  class=0  score=1.0000
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1618633260691_0.jpg  →  class=0  score=0.9996
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1619623948385_0.jpg  →  class=0  score=0.9995
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1620460846162_0.jpg  →  class=1  score=0.9999
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1633ddca-e0b3-4fed-9684-df4e39181e7b.jpg  →  class=0  score=0.9107
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1642559055721_0.jpg  →  class=0  score=0.9971
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1644206328927_0.jpg  →  class=0  score=1.0000
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1644290580234.jpg  →  class=0  score=0.9989
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1644805470465_0.jpg  →  class=0  score=0.9995
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1644807455733_0.jpg  →  class=0  score=0.9990
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1644892860584_0.jpg  →  class=0  score=0.9969
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1644975587670_0.jpg  →  class=1  score=0.9999
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1645067298199_0.jpg  →  class=0  score=0.9996
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1645405493708_0.jpg  →  class=0  score=0.9982
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1645682772493_0.jpg  →  class=0  score=0.9996
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1646015969267_0.jpg  →  class=0  score=0.9926
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1646965636900_0.jpg  →  class=1  score=0.9976
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1647232165472_0.jpg  →  class=0  score=0.9746
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1647397520071.jpg  →  class=0  score=0.9838
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1647487773329_0.jpg  →  class=1  score=0.9999
2026-08-07 13:25:46 | INFO     | classify.engine.predictor —   1647492072750_0.jpg  →  class=0  score=0.9982
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1647849429918_0.jpg  →  class=1  score=0.9968
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1647860953969_0.jpg  →  class=0  score=0.9999
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1647922139773_0.jpg  →  class=1  score=0.9998
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1648000986355_0.jpg  →  class=1  score=0.9960
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1648001684789_0.jpg  →  class=1  score=0.9999
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1648004210914_0.jpg  →  class=0  score=0.9997
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1648177580933_0.jpg  →  class=1  score=0.9969
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1648526003657_0.jpg  →  class=1  score=0.9999
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1648780187646_0.jpg  →  class=0  score=0.9995
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1648783907672_0.jpg  →  class=0  score=0.9999
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1649041283086_0.jpg  →  class=0  score=0.9998
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1650506787796_0.jpg  →  class=1  score=0.9998
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1666e6ed-f394-4d4d-b43a-1214b003b910_aligned.jpg  →  class=0  score=1.0000
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   16745a4e-ab30-46fe-8635-33c3aa7ef04a.jpg  →  class=0  score=0.5647
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   169db030-053a-43b4-b2cf-4d38109a75f2.jpg  →  class=0  score=0.9996
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   18884032-4417-46ee-a5fc-2458e61a40a7_aligned.jpg  →  class=0  score=0.9997
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   196e3ddc-5552-4ecc-9314-d2c1aba5e245.jpg  →  class=0  score=0.9998
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1a187a7a-0302-4bdd-b98e-19bdd0e22c2b.jpg  →  class=0  score=0.9972
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1aa4e1ff-d6a2-4642-acdf-852ecb0dbc5e.jpg  →  class=0  score=0.9944
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1abbf197-e50c-4563-85af-2741e9442e7b_aligned.jpg  →  class=0  score=0.9999
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1ad55cf7-2076-435a-85a7-2bdb4d60ee13_aligned.jpg  →  class=0  score=0.9914
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1b10d528-e66b-4d4f-92e0-8264928ae2b5_aligned.jpg  →  class=0  score=0.9999
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1b6ba8be-fdb0-48ca-8580-d2b80d64a434.jpg  →  class=0  score=0.9997
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1bafd8a9-6ccf-45ff-a13e-21ffc0ca97cb_aligned.jpg  →  class=0  score=0.9991
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1bc7641d-b1a4-45e8-98a6-5e1ba3f1554e_aligned.jpg  →  class=0  score=0.9998
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1c1642f6-35c3-4f44-ba8c-e3a8772f3321.jpg  →  class=0  score=0.9997
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1c72202b-3470-48f3-ac5a-717e680a14fa.jpg  →  class=0  score=0.9996
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1c8dad77-bb59-4ca4-bb26-48f6d40f4ccb.jpg  →  class=0  score=0.9999
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1c930fc6-9840-4603-971a-5753783302ea_aligned.jpg  →  class=0  score=0.9986
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1d46000c-9b1b-4cb1-b8e3-91ab8f0733e8_aligned.jpg  →  class=0  score=0.9977
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1d81db2e-25af-4dbe-a7c1-0572490838c5_aligned.jpg  →  class=0  score=1.0000
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1de3104f-2ff3-4f94-ad98-250d2ab8cfd6.jpg  →  class=0  score=0.9996
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1e87a3f1-93e5-4a0f-b37f-846ab5410790.jpg  →  class=0  score=0.9989
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   1e92fb0d-27e6-4db0-8a9e-fb2fb8c7e4be_aligned.jpg  →  class=0  score=0.9998
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   2 (33).jpg  →  class=1  score=0.9992
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   2 (39).jpg  →  class=1  score=0.9905
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20134a66-bc0b-4cec-bb77-b8e79bb0b14f.jpg  →  class=0  score=0.9990
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160509_094013.jpg  →  class=1  score=0.9090
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160509_094013_0.jpg  →  class=1  score=1.0000
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160608_091936_0.jpg  →  class=1  score=0.9686
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160610_113453.jpg  →  class=0  score=0.9762
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160614_122706_0.jpg  →  class=0  score=0.9938
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160615_111552_0.jpg  →  class=1  score=0.9986
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160617_112629_0.jpg  →  class=1  score=1.0000
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160617_112629_1.jpg  →  class=1  score=0.9998
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160617_142715.jpg  →  class=1  score=0.9999
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160617_142715_0.jpg  →  class=1  score=0.9959
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160617_142715_1.jpg  →  class=1  score=0.9960
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160617_154217.jpg  →  class=0  score=0.9968
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160617_154217_0.jpg  →  class=0  score=0.9996
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160617_154221.jpg  →  class=0  score=0.9945
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160617_154221_0.jpg  →  class=0  score=0.9998
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160628_111211.jpg  →  class=1  score=1.0000
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160704_085056_0.jpg  →  class=1  score=0.9987
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160704_093450.jpg  →  class=0  score=0.9949
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160704_102644.jpg  →  class=0  score=0.9983
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160704_102644_0.jpg  →  class=0  score=0.9984
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160704_102649.jpg  →  class=0  score=0.9804
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160704_102649_0.jpg  →  class=0  score=0.9914
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160704_124400.jpg  →  class=0  score=0.9970
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160704_124400_0.jpg  →  class=0  score=0.9983
2026-08-07 13:25:47 | INFO     | classify.engine.predictor —   20160704_124404_0.jpg  →  class=0  score=0.9672

In [6]:
df

                                                   file  class_index     score
0     datasets/dataset/train/0028e49b-4e02-4ed1-b9c6...            0  0.999795
1     datasets/dataset/train/00dd301c-c6c7-4fca-b7c6...            0  0.999957
2     datasets/dataset/train/0107d7c0-d826-40a7-8a5f...            0  0.998721
3     datasets/dataset/train/015a6379-065e-4ce3-a2e5...            0  0.954086
4     datasets/dataset/train/01add812-5843-4f75-a2fa...            0  0.981897
...                                                 ...          ...       ...
3494  datasets/dataset/train/z782380696570_07ed9dea7...            1  0.999978
3495  datasets/dataset/train/z786023933745_09a681ea9...            0  0.997646
3496  datasets/dataset/train/z792241892678_8859f0f19...            0  0.998258
3497  datasets/dataset/train/z793142113256_d34482ab9...            1  0.999843
3498  datasets/dataset/train/z800861086002_d6ce5804e...            1  0.999006

[3499 rows x 3 columns]

In [8]:
labels = ["colored", "photo"]


df["predicted_label"] = df["class_index"].apply(lambda x: labels[x])
df

,file,class_index,score,predicted_label
0,datasets/dataset/train/0028e49b-4e02-4ed1-b9c6...,0,0.999795,colored
1,datasets/dataset/train/00dd301c-c6c7-4fca-b7c6...,0,0.999957,colored
2,datasets/dataset/train/0107d7c0-d826-40a7-8a5f...,0,0.998721,colored
3,datasets/dataset/train/015a6379-065e-4ce3-a2e5...,0,0.954086,colored
4,datasets/dataset/train/01add812-5843-4f75-a2fa...,0,0.981897,colored
...,...,...,...,...
3494,datasets/dataset/train/z782380696570_07ed9dea7...,1,0.999978,photo
3495,datasets/dataset/train/z786023933745_09a681ea9...,0,0.997646,colored
3496,datasets/dataset/train/z792241892678_8859f0f19...,0,0.998258,colored
3497,datasets/dataset/train/z793142113256_d34482ab9...,1,0.999843,photo
3498,datasets/dataset/train/z800861086002_d6ce5804e...,1,0.999006,photo

In [9]:
filenames = df["file"]
labels = df["predicted_label"]

In [10]:
import os
import shutil
def copy_files_to_folder(paths, labels, dest_folder):
    for filename, label in zip(paths, labels):
        label_folder = os.path.join(dest_folder, label)
        os.makedirs(label_folder, exist_ok=True)
        dest_path = os.path.join(label_folder, os.path.basename(filename))
        shutil.copy(filename, dest_path)

In [11]:
copy_files_to_folder(df["file"], df["predicted_label"], "predicted_results")

In [24]:
import glob
from sklearn.model_selection import train_test_split

input_dir = "predicted_results"
output_folder = "dataset_4"

for label in os.listdir(input_dir):
    label_folder = os.path.join(input_dir, label)
    if os.path.isdir(label_folder):
        image_paths = glob.glob(os.path.join(label_folder, "*"))
        train_paths, val_paths = train_test_split(image_paths, test_size=0.2, random_state=42)

        # Create output directories for train and validation sets
        train_output_dir = os.path.join(output_folder, "train", label)
        val_output_dir = os.path.join(output_folder, "val", label)
        os.makedirs(train_output_dir, exist_ok=True)
        os.makedirs(val_output_dir, exist_ok=True)\section{Generalization to Real-World and Telephony Conditions}


        # Copy training images
        for path in train_paths:
            shutil.copy(path, os.path.join(train_output_dir, os.path.basename(path)))

        # Copy validation images
        for path in val_paths:
            shutil.copy(path, os.path.join(val_output_dir, os.path.basename(path)))

In [26]:
import pathlib
import json

folder = r"predicted_results/photo"
image_paths = os.listdir(folder)  # Adjust the pattern if needed

json_dump = dict()
json_file = []

for image_path in image_paths:
    json_file.append({
        "image_path": image_path,
        "label": ["photo"]
    })
print(json_file)

with open("tags.json", "w") as f:
    json.dump(json_file, f, indent=4)

[{'image_path': '1 (8) dated_0.jpg', 'label': ['photo']}, {'image_path': '1 (8) dated_1.jpg', 'label': ['photo']}, {'image_path': '1 TONG THE  (8).jpg', 'label': ['photo']}, {'image_path': '1 TONG THE  (8)_0.jpg', 'label': ['photo']}, {'image_path': '1 TONG THE  (8)_1.jpg', 'label': ['photo']}, {'image_path': '1468486733824_11240_0.jpg', 'label': ['photo']}, {'image_path': '1469618546810_15097_1.jpg', 'label': ['photo']}, {'image_path': '1470039818684_15971_1.jpg', 'label': ['photo']}, {'image_path': '1470210967795_16203_0.jpg', 'label': ['photo']}, {'image_path': '1473152626281_23391.jpg', 'label': ['photo']}, {'image_path': '1473843077455_26330_1.jpg', 'label': ['photo']}, {'image_path': '1476197219764_32888_0.jpg', 'label': ['photo']}, {'image_path': '1476267278670_33132_1.jpg', 'label': ['photo']}, {'image_path': '1476340747997_33524_0.jpg', 'label': ['photo']}, {'image_path': '1476958922728_34948_0.jpg', 'label': ['photo']}, {'image_path': '1477105354275_35279_1.jpg', 'label': ['photo']}, {'image_path': '1479125511611_39662_0.jpg', 'label': ['photo']}, {'image_path': '1479125825126_39669_0.jpg', 'label': ['photo']}, {'image_path': '1613717080545_0.jpg', 'label': ['photo']}, {'image_path': '1620460846162_0.jpg', 'label': ['photo']}, {'image_path': '1644975587670_0.jpg', 'label': ['photo']}, {'image_path': '1646965636900_0.jpg', 'label': ['photo']}, {'image_path': '1647487773329_0.jpg', 'label': ['photo']}, {'image_path': '1647849429918_0.jpg', 'label': ['photo']}, {'image_path': '1647922139773_0.jpg', 'label': ['photo']}, {'image_path': '1648000986355_0.jpg', 'label': ['photo']}, {'image_path': '1648001684789_0.jpg', 'label': ['photo']}, {'image_path': '1648177580933_0.jpg', 'label': ['photo']}, {'image_path': '1648526003657_0.jpg', 'label': ['photo']}, {'image_path': '1650506787796_0.jpg', 'label': ['photo']}, {'image_path': '2 (33).jpg', 'label': ['photo']}, {'image_path': '2 (39).jpg', 'label': ['photo']}, {'image_path': '20160509_094013.jpg', 'label': ['photo']}, {'image_path': '20160509_094013_0.jpg', 'label': ['photo']}, {'image_path': '20160608_091936_0.jpg', 'label': ['photo']}, {'image_path': '20160615_111552_0.jpg', 'label': ['photo']}, {'image_path': '20160617_112629_0.jpg', 'label': ['photo']}, {'image_path': '20160617_112629_1.jpg', 'label': ['photo']}, {'image_path': '20160617_142715.jpg', 'label': ['photo']}, {'image_path': '20160617_142715_0.jpg', 'label': ['photo']}, {'image_path': '20160617_142715_1.jpg', 'label': ['photo']}, {'image_path': '20160628_111211.jpg', 'label': ['photo']}, {'image_path': '20160704_085056_0.jpg', 'label': ['photo']}, {'image_path': '20160706_111218_0.jpg', 'label': ['photo']}, {'image_path': '20160706_111218_1.jpg', 'label': ['photo']}, {'image_path': '20160706_115311.jpg', 'label': ['photo']}, {'image_path': '20160707_083810.jpg', 'label': ['photo']}, {'image_path': '20160707_083810_0.jpg', 'label': ['photo']}, {'image_path': '20160707_083810_1.jpg', 'label': ['photo']}, {'image_path': '20160711_080528_0.jpg', 'label': ['photo']}, {'image_path': '20160711_080533_0.jpg', 'label': ['photo']}, {'image_path': '20160712_090316_0.jpg', 'label': ['photo']}, {'image_path': '20160713_094550.jpg', 'label': ['photo']}, {'image_path': '20160713_094550_0.jpg', 'label': ['photo']}, {'image_path': '20160719_113343.jpg', 'label': ['photo']}, {'image_path': '20160719_113343_0.jpg', 'label': ['photo']}, {'image_path': '20160719_113355.jpg', 'label': ['photo']}, {'image_path': '20160719_113355_0.jpg', 'label': ['photo']}, {'image_path': '20160728_084303_0.jpg', 'label': ['photo']}, {'image_path': '20160728_084303_1.jpg', 'label': ['photo']}, {'image_path': '20160801_104224.jpg', 'label': ['photo']}, {'image_path': '20160801_104224_0.jpg', 'label': ['photo']}, {'image_path': '20160817_152452_2.jpg', 'label': ['photo']}, {'image_path': '20160818_080650_0.jpg', 'label': ['photo']}, {'image_path': '20160822_101820.jpg', 'label': ['photo']}, {'image_path': '20160822_101820_0.jpg', 'label': ['photo']}, {'image_path': '20160822_101824.jpg', 'label': ['photo']}, {'image_path': '20160825_094302.jpg', 'label': ['photo']}, {'image_path': '20160825_094302_1.jpg', 'label': ['photo']}, {'image_path': '20160825_094302_2.jpg', 'label': ['photo']}, {'image_path': '20160829_084700.jpg', 'label': ['photo']}, {'image_path': '20160829_084700_0.jpg', 'label': ['photo']}, {'image_path': '20160905_100809.jpg', 'label': ['photo']}, {'image_path': '20160905_100809_0.jpg', 'label': ['photo']}, {'image_path': '20160905_100815.jpg', 'label': ['photo']}, {'image_path': '20160905_100815_0.jpg', 'label': ['photo']}, {'image_path': '20160907_083832_0.jpg', 'label': ['photo']}, {'image_path': '20160907_083837.jpg', 'label': ['photo']}, {'image_path': '20160912_093209_0.jpg', 'label': ['photo']}, {'image_path': '20160912_093209_1.jpg', 'label': ['photo']}, {'image_path': '20160915_084420.jpg', 'label': ['photo']}, {'image_path': '20160915_084420_0.jpg', 'label': ['photo']}, {'image_path': '20160919_081559.jpg', 'label': ['photo']}, {'image_path': '20160919_081559_0.jpg', 'label': ['photo']}, {'image_path': '20160919_081605.jpg', 'label': ['photo']}, {'image_path': '20160919_085616.jpg', 'label': ['photo']}, {'image_path': '20160919_085616_0.jpg', 'label': ['photo']}, {'image_path': '20160920_094454.jpg', 'label': ['photo']}, {'image_path': '20160920_094454_0.jpg', 'label': ['photo']}, {'image_path': '20160921_110302_0.jpg', 'label': ['photo']}, {'image_path': '20160929_102006_0.jpg', 'label': ['photo']}, {'image_path': '20161003_091450.jpg', 'label': ['photo']}, {'image_path': '20161003_091450_0.jpg', 'label': ['photo']}, {'image_path': '20161007_085509.jpg', 'label': ['photo']}, {'image_path': '20161007_085513_0.jpg', 'label': ['photo']}, {'image_path': '20161007_093721.jpg', 'label': ['photo']}, {'image_path': '20161007_093721_0.jpg', 'label': ['photo']}, {'image_path': '20161010_092438.jpg', 'label': ['photo']}, {'image_path': '20161013_081445_0.jpg', 'label': ['photo']}, {'image_path': '20161024_143220.jpg', 'label': ['photo']}, {'image_path': '20161024_143220_0.jpg', 'label': ['photo']}, {'image_path': '20161024_143220_1.jpg', 'label': ['photo']}, {'image_path': '20161025_092944_0.jpg', 'label': ['photo']}, {'image_path': '20161025_094658_1.jpg', 'label': ['photo']}, {'image_path': '20161026_093739_0.jpg', 'label': ['photo']}, {'image_path': '20161026_110157_0.jpg', 'label': ['photo']}, {'image_path': '20161114_082812_0.jpg', 'label': ['photo']}, {'image_path': '20161114_082818_0.jpg', 'label': ['photo']}, {'image_path': '20161114_082818_1.jpg', 'label': ['photo']}, {'image_path': '20161114_085222.jpg', 'label': ['photo']}, {'image_path': '20161114_112048.jpg', 'label': ['photo']}, {'image_path': '20161114_112048_0.jpg', 'label': ['photo']}, {'image_path': '20161114_112048_1.jpg', 'label': ['photo']}, {'image_path': '20161114_112104_0.jpg', 'label': ['photo']}, {'image_path': '20161114_112104_1.jpg', 'label': ['photo']}, {'image_path': '20161123_122539_0.jpg', 'label': ['photo']}, {'image_path': '20161123_122705_1.jpg', 'label': ['photo']}, {'image_path': '20161128_102901.jpg', 'label': ['photo']}, {'image_path': '20161130_144818.jpg', 'label': ['photo']}, {'image_path': '20161130_144824.jpg', 'label': ['photo']}, {'image_path': '20161130_144824_0.jpg', 'label': ['photo']}, {'image_path': '20161206_091742_0.jpg', 'label': ['photo']}, {'image_path': '20161206_091742_1.jpg', 'label': ['photo']}, {'image_path': '20161206_092940_0.jpg', 'label': ['photo']}, {'image_path': '20161206_094309.jpg', 'label': ['photo']}, {'image_path': '20161206_094309_0.jpg', 'label': ['photo']}, {'image_path': '20161206_154031_0.jpg', 'label': ['photo']}, {'image_path': '20161206_154031_1.jpg', 'label': ['photo']}, {'image_path': '20161207_105308_0.jpg', 'label': ['photo']}, {'image_path': '20161209_082345_0.jpg', 'label': ['photo']}, {'image_path': '20161209_082345_1.jpg', 'label': ['photo']}, {'image_path': '20161209_082351_0.jpg', 'label': ['photo']}, {'image_path': '20161209_082351_1.jpg', 'label': ['photo']}, {'image_path': '20161213_092849.jpg', 'label': ['photo']}, {'image_path': '20161213_092849_0.jpg', 'label': ['photo']}, {'image_path': '20161213_092849_1.jpg', 'label': ['photo']}, {'image_path': '20161213_092857_0.jpg', 'label': ['photo']}, {'image_path': '20161213_092857_1.jpg', 'label': ['photo']}, {'image_path': '20161216_115246_0.jpg', 'label': ['photo']}, {'image_path': '20161219_082402_0.jpg', 'label': ['photo']}, {'image_path': '20161219_082402_1.jpg', 'label': ['photo']}, {'image_path': '20161220_091227.jpg', 'label': ['photo']}, {'image_path': '20161220_091227_0.jpg', 'label': ['photo']}, {'image_path': '20161220_091251.jpg', 'label': ['photo']}, {'image_path': '20161220_091251_0.jpg', 'label': ['photo']}, {'image_path': '20170104_200502_0.jpg', 'label': ['photo']}, {'image_path': '20170105_141630_0.jpg', 'label': ['photo']}, {'image_path': '20170114_095418_0.jpg', 'label': ['photo']}, {'image_path': '20170116_112015_0.jpg', 'label': ['photo']}, {'image_path': '20170116_155200_1.jpg', 'label': ['photo']}, {'image_path': '20170116_160319_0.jpg', 'label': ['photo']}, {'image_path': '20170121_105153_1.jpg', 'label': ['photo']}, {'image_path': '20170202_130831_0.jpg', 'label': ['photo']}, {'image_path': '20170206_080725.jpg', 'label': ['photo']}, {'image_path': '20170206_080725_0.jpg', 'label': ['photo']}, {'image_path': '20170208_112409.jpg', 'label': ['photo']}, {'image_path': '20170209_080633_0.jpg', 'label': ['photo']}, {'image_path': '20170209_104405_0.jpg', 'label': ['photo']}, {'image_path': '20170213_081413_0.jpg', 'label': ['photo']}, {'image_path': '20170213_081715.jpg', 'label': ['photo']}, {'image_path': '20170213_090218_0.jpg', 'label': ['photo']}, {'image_path': '20170213_095755_0.jpg', 'label': ['photo']}, {'image_path': '20170214_080656_0.jpg', 'label': ['photo']}, {'image_path': '20170214_105948_0.jpg', 'label': ['photo']}, {'image_path': '20170224_083733_0.jpg', 'label': ['photo']}, {'image_path': '20170307_103756.jpg', 'label': ['photo']}, {'image_path': '20170307_151050.jpg', 'label': ['photo']}, {'image_path': '20170307_164423_0.jpg', 'label': ['photo']}, {'image_path': '20170308_105001_0.jpg', 'label': ['photo']}, {'image_path': '20170320_082044_0.jpg', 'label': ['photo']}, {'image_path': '20170324_160945_0.jpg', 'label': ['photo']}, {'image_path': '20170324_161035_0.jpg', 'label': ['photo']}, {'image_path': '20170327_083601_0.jpg', 'label': ['photo']}, {'image_path': '20170328_052247_0.jpg', 'label': ['photo']}, {'image_path': '20170328_080335_0.jpg', 'label': ['photo']}, {'image_path': '20170328_083913_0.jpg', 'label': ['photo']}, {'image_path': '20170330_160532.jpg', 'label': ['photo']}, {'image_path': '20170412_102654_0.jpg', 'label': ['photo']}, {'image_path': '20170413_164248_0.jpg', 'label': ['photo']}, {'image_path': '20170414_080245_0.jpg', 'label': ['photo']}, {'image_path': '20170417_084714_0.jpg', 'label': ['photo']}, {'image_path': '20170417_180351_0.jpg', 'label': ['photo']}, {'image_path': '20170418_060907_0.jpg', 'label': ['photo']}, {'image_path': '20170503_110327_1.jpg', 'label': ['photo']}, {'image_path': '20170503_110630_1.jpg', 'label': ['photo']}, {'image_path': '20170506_094202.jpg', 'label': ['photo']}, {'image_path': '20170506_094202_0.jpg', 'label': ['photo']}, {'image_path': '20170511_112409_0.jpg', 'label': ['photo']}, {'image_path': '20170522_080318_0.jpg', 'label': ['photo']}, {'image_path': '20170526_083407.jpg', 'label': ['photo']}, {'image_path': '20170605_100824_0.jpg', 'label': ['photo']}, {'image_path': '20170605_101107_0.jpg', 'label': ['photo']}, {'image_path': '20170613_082738_0.jpg', 'label': ['photo']}, {'image_path': '20170614_083015_0.jpg', 'label': ['photo']}, {'image_path': '20170614_144918_0.jpg', 'label': ['photo']}, {'image_path': '20170615_102640_0.jpg', 'label': ['photo']}, {'image_path': '20170619_085724_0.jpg', 'label': ['photo']}, {'image_path': '20170620_105258.jpg', 'label': ['photo']}, {'image_path': '20170620_151100_0.jpg', 'label': ['photo']}, {'image_path': '20170621_100127_0.jpg', 'label': ['photo']}, {'image_path': '20170621_102331_0.jpg', 'label': ['photo']}, {'image_path': '20170622_110210_0.jpg', 'label': ['photo']}, {'image_path': '20170703_133558_0.jpg', 'label': ['photo']}, {'image_path': '20170704_151859_0.jpg', 'label': ['photo']}, {'image_path': '20170705_125616_0.jpg', 'label': ['photo']}, {'image_path': '20170710_082133_0.jpg', 'label': ['photo']}, {'image_path': '20170711_101627_0.jpg', 'label': ['photo']}, {'image_path': '20170717_105354_0.jpg', 'label': ['photo']}, {'image_path': '20170717_105620_0.jpg', 'label': ['photo']}, {'image_path': '20170717_111656_0.jpg', 'label': ['photo']}, {'image_path': '20170718_154220_0.jpg', 'label': ['photo']}, {'image_path': '20170720_083941_0.jpg', 'label': ['photo']}, {'image_path': '20170724_080539_0.jpg', 'label': ['photo']}, {'image_path': '20170727_220258_0.jpg', 'label': ['photo']}, {'image_path': '20170801_095347_0.jpg', 'label': ['photo']}, {'image_path': '20170805_112046_0.jpg', 'label': ['photo']}, {'image_path': '20170810_131340_1.jpg', 'label': ['photo']}, {'image_path': '20170810_142142_0.jpg', 'label': ['photo']}, {'image_path': '20170918_094920_1.jpg', 'label': ['photo']}, {'image_path': '20170925_104934_0.jpg', 'label': ['photo']}, {'image_path': '20171005_111855_0.jpg', 'label': ['photo']}, {'image_path': '20171013_223331_0.jpg', 'label': ['photo']}, {'image_path': '20180115_104800_0.jpg', 'label': ['photo']}, {'image_path': '20180115_112556_0.jpg', 'label': ['photo']}, {'image_path': '20180117_094433_0.jpg', 'label': ['photo']}, {'image_path': '20180119_085727_0.jpg', 'label': ['photo']}, {'image_path': '20181001_133613_0.jpg', 'label': ['photo']}, {'image_path': '20181004_110028_0.jpg', 'label': ['photo']}, {'image_path': '20181015_083909_0.jpg', 'label': ['photo']}, {'image_path': '20211202_142537_0.jpg', 'label': ['photo']}, {'image_path': '20211214_094140_0.jpg', 'label': ['photo']}, {'image_path': '20211222_093235_0.jpg', 'label': ['photo']}, {'image_path': '20211222_102544_0.jpg', 'label': ['photo']}, {'image_path': '20211229_102101_0.jpg', 'label': ['photo']}, {'image_path': '20211229_103617_0.jpg', 'label': ['photo']}, {'image_path': '20220104_093926_0.jpg', 'label': ['photo']}, {'image_path': '20220104_112556_0.jpg', 'label': ['photo']}, {'image_path': '20220107_090442_0.jpg', 'label': ['photo']}, {'image_path': '20220110_080447_0.jpg', 'label': ['photo']}, {'image_path': '20220111_093952_0.jpg', 'label': ['photo']}, {'image_path': '20220113_093812_1.jpg', 'label': ['photo']}, {'image_path': '3 (2).jpg', 'label': ['photo']}, {'image_path': '3 (3).jpg', 'label': ['photo']}, {'image_path': 'CCVX (1)_0.jpg', 'label': ['photo']}, {'image_path': 'CVX (2)_0.jpg', 'label': ['photo']}, {'image_path': 'CamScanner 06-02-2021 15.03_14_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_02072016_125453_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_0348_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_0378.jpg', 'label': ['photo']}, {'image_path': 'IMG_0630_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_0962 (2)_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_1132_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_1640_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_1781_1.jpg', 'label': ['photo']}, {'image_path': 'IMG_1844_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_1975_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_1977.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210222_085549_762_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210222_101241_844_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210303_084327_000_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210309_092938_458_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210325_095810_091_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210325_110354_978_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210325_134939_200_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210329_094454_196_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210402_090853_659_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210409_083013_713_1.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210413_101305_325_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210416_081255_197_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210426_095252_071_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210426_095553_832_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210426_123016_954_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210427_083136_715_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210427_110745_715_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210504_081441_898_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210504_082234_231_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210508_104259_610_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210508_141752_971_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210511_101904_397_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210512_120435_980_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210514_102228_191_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210517_134155_530_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210518_085610_919_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210518_101449_452_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210520_094433_450_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210521_160235_106_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210526_100620_825_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210527_032343_1.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210531_083956_308_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210531_101757_964_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210608_092129_099_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210614_102050_946_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210614_103741_718_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20210615_102959_463_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20211005_083501_390_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20211005_100720_194_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20211005_100721_784_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20211013_101645_810_1.jpg', 'label': ['photo']}, {'image_path': 'IMG_20211015_103841_928_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20211025_112800_858_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20211029_090500_045_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20211104_130230_323_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20211110_100730_428_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_20220210_091419_304_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_4052_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_4832_1.jpg', 'label': ['photo']}, {'image_path': 'IMG_5228_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_5858_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_6219_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_8317_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_8606_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_8717_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_8987_2.jpg', 'label': ['photo']}, {'image_path': 'IMG_9181_0.jpg', 'label': ['photo']}, {'image_path': 'IMG_UPLOAD_20210303_083159_0.jpg', 'label': ['photo']}, {'image_path': 'TimePhoto_20210610_055425_0.jpg', 'label': ['photo']}, {'image_path': 'align_1 (19).jpg', 'label': ['photo']}, {'image_path': 'align_1 (8) dated.jpg', 'label': ['photo']}, {'image_path': 'align_1468931959046_12884.jpg', 'label': ['photo']}, {'image_path': 'align_1469618546810_15097.jpg', 'label': ['photo']}, {'image_path': 'align_1470210967795_16203.jpg', 'label': ['photo']}, {'image_path': 'align_1473152626281_23391.jpg', 'label': ['photo']}, {'image_path': 'align_1474342966692_28069.jpg', 'label': ['photo']}, {'image_path': 'align_1475664392017_31648.jpg', 'label': ['photo']}, {'image_path': 'align_1476261369863_33069.jpg', 'labe